name: Docker Compose Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: true
          # tags: your-registry/your-image:latest

      - name: Deploy with Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          up-flags: "-d"